server.port: 8080

spring:
  application.name: e-disco-vinil-api
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./disco-vinil-data
    username: sa
    platform: h2-dev
    continue-on-error: true


logging:
  path: ./logs
  file: ${spring.application.name}.log
  level:
    root: WARN
    org.hibernate: ERROR
    org.springframework.web: INFO
    org.springframework.web.client: DEBUG
    com.github.eltonsandre: DEBUG

com.spotify:
  api:
    url-base: https://api.spotify.com/v1
    oauth:
      url-token: https://accounts.spotify.com/api/token
      cliente_id: 2410dad2ce8c460e984c2434d6a1a5b6
      cliente_secret: fadd0a1714e94455b58e6ba8fc484f71
      access-token: MjQxMGRhZDJjZThjNDYwZTk4NGMyNDM0ZDZhMWE1YjY6ZmFkZDBhMTcxNGU5NDQ1NWI1OGU2YmE4ZmM0ODRmNzE=
      

