INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('POP','DOMINGO' , 25);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('POP','SEGUNDA' ,7);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('POP','TERCA'   ,6);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('POP','QUARTA'  ,2);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('POP','QUINTA'  ,10);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('POP','SEXTA'   ,15);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('POP','SABADO'  ,20);

INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('MPB','DOMINGO' ,30);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('MPB','SEGUNDA' ,5);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('MPB','TERCA'   ,10);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('MPB','QUARTA'  ,15);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('MPB','QUINTA'  ,20);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('MPB','SEXTA'   ,25);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('MPB','SABADO'  ,30);

INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('CLASSIC','DOMINGO' ,35);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('CLASSIC','SEGUNDA' ,3);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('CLASSIC','TERCA'   ,5);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('CLASSIC','QUARTA'  ,8);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('CLASSIC','QUINTA'  ,13);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('CLASSIC','SEXTA'   ,18);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('CLASSIC','SABADO'  ,25);

INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('ROCK','DOMINGO' ,40);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('ROCK','SEGUNDA' ,10);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('ROCK','TERCA'   ,15);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('ROCK','QUARTA'  ,15);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('ROCK','QUINTA'  ,15);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('ROCK','SEXTA'   ,20);
INSERT INTO CASHBACK (GENERO, DIA_SEMANA, PORCENTAGEM) VALUES ('ROCK','SABADO'  ,40);